# Installs dependencies for the Myricom SNF drivers then downloads and installs those drivers.

# Modern defaults we want
boot-location: modules
tmp-is-dir: true

# Required by Ignition, and makes the system not compatible with Anaconda
machineid-compat: false

packages:
  - gcc
  - kernel-devel
  - glibc
  - libpcap
  - myri_snf

postprocess:
  # Download and install Myricom SNF 3 drivers.
  - |
    #!/usr/bin/env bash
    echo "Installing SNF" # testing
